### ISSUE TITLE
Add support for World-Gen on 'Mod-Dirt' blocks

### ISSUE THREAD

**Issue by MidnightsFX** [GrowthcraftCE/Growthcraft-1.7#84] opened 2015-09-18 21:01 UTC
Here is the mod in specific I was thinking about. The alternative 'dirt' blocks used (Andisol etc) are not seen as valid spawn points for Growthcraft. 

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294692-enhanced-biomes-2-5-nearly-100-new-biomes-20-10-14

**Comment by Ar97x** [comment] 2015-09-20 04:27
This is cool. We should try to do it.

**Comment by IceDragon200** [comment] 2015-09-28 23:28
@MidnightsFX  Valid spawn points? Is that for village structures or am I missing something?
If you can provide another open source mod that works as intended that would help us bigtime for reference

**Comment by MidnightsFX** [comment] 2015-09-29 01:35
@IceDragon200 I'm actually talking about spawning the flora and shrubberies. I am drawing a blank on open source mods which I could point to for examples.

But, what I mean is this- when growthcraft or another mod which spawns flowers, trees or other shrubs goes to place one in the world it seeks a valid dirt block to place its greenery on. Since this mod uses various different dirt blocks, any biomes that do not use the vanilla dirt block are immediately seen as invalid spawn points. Which means that patches of bambo or other trees specifically generated by this mod won't show up in a world generated with a mod which uses a dirt block variant.

It could also be that the shrubs/trees are being destroyed shortly after placement because the 'dirt' they were placed on has a different damage value than the default and thus seen as an invalid surface to grow on.

Hope that explains it, sorry I couldn't think of any open source mod that does this already.

**Comment by IceDragon200** [comment] 2015-09-29 02:20
@MidnightsFX 
Trees aren't destroyed by changing dirt blocks; flowers, torches, doors, redstone (pretty much anything that relies on the presence of a specific block below) are broken and left as items, but I see your problem.

In short, because our structures generate specifically on minecraft dirt/grass blocks they won't generate  on these new dirt blocks.

There's nothing much we can do about that unless that mod has an API, OR it exposes the OreDictionary names for their dirt blocks (I'm pulling "maybe this could work" here).

Our best bet would be an API, or dirt block interface

``` java
class DirtChecker 
{
  static public boolean isAwesomeDirt(Block block) 
  {
     if (block == net.minecraft.block.Blocks.dirt) {
       return true;
     } else if (block instanceof FancyDirt) {
       return true;
     } else {
       // nope not dirt
       return false;
     }
  }
}

interface FancyDirt 
{  
  // I wonder, can we have empty interfaces in java, need to look into this
  public boolean isAwesomeDirt();
}

class AwesomeDirt extends Block implements isAwesomeDirt
{
  public boolean isAwesomeDirt() {
    return true;
  }
}
```

If you'd like to see this feature, poke the mod author about an API :)

**Comment by MidnightsFX** [comment] 2015-09-29 02:23
Will do! He is decently responsive so I'll see if he has anything about a possible api or an OreDic for the dirt.

**Comment by MidnightsFX** [comment] 2015-09-29 23:43
So this is what the author of EB said. I'm not a Java dev so unfortunately I don't know if this is exactly what your looking for- but it looks like its a step in the right direction.

> Okay, yes, it is possible to grow stuff on my dirt blocks, and any other mods' dirt blocks, as long as they have been programmed correctly.
> 
> Have your crop implement IPlantable.
> 
> Then, use this:
> 
> ``` java
> public EnumPlantType getPlantType(IBlockAccess world, int x, int y, int z) {
>  return EnumPlantType.InsertPlantTypeHere;
> }
> ```
> 
> to set the type of soil that the plant will look for.
> 
> Finally, replace
> 
> ``` java
> public boolean canBlockStay(World p_149718_1_, int p_149718_2_, int p_149718_3_, int p_149718_4_) {
>  return true;
> }
> ```
> 
> with
> 
> ``` java
> public boolean canBlockStay(World p_149718_1_, int p_149718_2_, int p_149718_3_, int p_149718_4_) {
>  Block block = p_149718_1_.getBlock(p_149718_2_, p_149718_3_ - 1, p_149718_4_);
>  return block.canSustainPlant(p_149718_1_, p_149718_2_, p_149718_3_ - 1, p_149718_4_, ForgeDirection.UP, this);
> }
> ```
> 
> This should work nicely, and is the correct way to check for soils. Also, if you ever need to check during generation, use the block.canSustainPlant code, but replace 'this' with your crop.

Hopefully that is helpful. I dont know too much about minecraft modding - or java dev at all actually.
But, here are the classes he is talking about from what I can see.
[EnumPlantType](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/EnumPlantType.java)
[IPlantable](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/IPlantable.java)

And the thread/Authors response as quoted from [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294692-enhanced-biomes-2-5-nearly-100-new-biomes-20-10-14?page=39#c782) SMEZ1234 answers this question towards the bottom of the linked post.

**Comment by IceDragon200** [comment] 2015-09-30 17:32
@MidnightsFX Ok, I got something, its probably a mess, but can you give it a test? look at #89 for a test build

**Comment by MidnightsFX** [comment] 2015-09-30 19:52
I will definitely take a look at it! I should be able to give you some useful results tomorrow.

**Comment by MidnightsFX** [comment] 2015-10-01 01:18
@IceDragon200 
Ok it looks like something is off about Build #89. Its failing to init, here's the trace.

http://pastebin.com/2Kqq3SUb

Its failing to find 'dye' from the cellar module.

**Comment by IceDragon200** [comment] 2015-10-01 02:43
@MidnightsFX 
Ah, I built it using the wrong workspace, -.-; its painful having to trash workspaces everytime I change branches, I've added 2 more builds, use `build2`, that should work (I hope)

**Comment by MidnightsFX** [comment] 2015-10-01 03:14
@IceDragon200 Excellent, could you give me a link to build 2? I see build 1 in #89 but no build two.

(build 1 also crashed with the same trace)

**Comment by IceDragon200** [comment] 2015-10-01 14:53
@MidnightsFX [build 2](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.2.2/growthcraft-1.7.10-2.2.2-complete_iplantable-build2.jar)

My internet derped on me yesterday when I updated the links, I guess it failed :(

For future reference, you can grab any of the links
`https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.2.2/growthcraft-1.7.10-2.2.2-complete_iplantable-build1.jar`

And replace the `build1` with the next number, `build2`, `build3` etc..

**Comment by Sunconure11** [comment] 2015-10-01 23:53
Biomes O Plenty also has its own soil variants. If those are not supported, you might want to support that as well.

**Comment by IceDragon200** [comment] 2015-10-02 01:23
@Sunconure11  It should work, assuming it works the same way Enhanced Biomes does it

**Comment by MidnightsFX** [comment] 2015-10-02 03:03
@IceDragon200  Ok so- Here's how it looks (Build 2).

Working, Growing, Planting, spawning- etc.
- Hops
- Grapes
- Apple Trees
- Beehives
- Village Generation / Planting

What doesn't work as expected:
- Rice Fields - Can't make one by re-hoeing farmland (dirt or mod-dirts)
- Bamboo - As soon as it grows/spawns it breaks (bamboo shoots plant correctly on all the new dirt, but break on growth).

I will take a look at Biome's O Plenty

**Comment by IceDragon200** [comment] 2015-10-02 03:38
@MidnightsFX 
**Rice Fields**
You don't plant them on regular farmland, you plant them in a paddy filled with water, you first `hoe` the dirt and then right click using a `shovel` to make a paddy, if it's not filled with water, you can fill it with a bucket of water.

Since they don't work on regular farmland, I can say proudly that they are working correctly, the only issue is that paddies require vanilla dirt (I could be wrong)

**Bamboo**
Fixed, ~~uploading~~ uploaded [build 3](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.2.2/growthcraft-1.7.10-2.2.2-complete_iplantable-build3.jar) now

**Comment by MidnightsFX** [comment] 2015-10-02 05:12
@IceDragon200  Excellent, and thanks for that tip- apparently its been a while for me!

Also, went through the build - and it looks good! I will test on Biome's O Plenty in just a second but I expect it to be working as intended. Thanks for your work on this!

It looks like Biome's O Plenty works fine also, as expected (Biomes O Plenty is still an unstable mod).

**Comment by IceDragon200** [comment] 2015-10-02 18:53
@MidnightsFX Closing this issue since the changes have been merged

**Closed as completed by IceDragon200** 2015-10-02 18:53 UTC
