### ISSUE TITLE
Several things not working - Growthcraft Milk 2.6.3 with custom modpack

### ISSUE THREAD

**Issue by plugnplay0** [GrowthcraftCE/Growthcraft-1.7#414] opened 2016-09-09 19:42 UTC
Growthcraft Milk doesn't seem to be working with my modpack. As far as I can see:
1. The pancheon just doesn't do anything. I put a milk bucket in it but then nothing ever happens, using Waila I can only see 'Tank 1 : 1000 / 1000 mB of Milk', and tanks 2 & 3 are empty
2. I can't find any thisles but maybe I'm not looking where I should
3. When I kill a calf, I do loot stomachs but can't pick them up, they just keep floating above floor and won't come into my inventory. Though I can make Rennet if I /give me the stomachs.

I was using Growthcraft Community Edition 2.5.2 but when I saw it not working I moved to latest build 2.6.3 but that didn't change anything. My modpack is a custom one running in Minecraft 1.7.10, please see the list of mods: 
[modlist.txt](https://github.com/GrowthcraftCE/Growthcraft-1.7/files/464674/modlist.txt)
I can't find any clue no matter how I search in Google.
Are there any known incompatibilities that I am not aware of?

**Comment by IceDragon200** [comment] 2016-09-09 20:37
@plugnplay0 
1. Which mod added the milk? (We support our own and Forestry's in 2.6)
2. Thistle was disabled by default due to several complains about the aggressive world gen, you can find `thistle seeds` in grass now, you can always re-enable the world gen
3. Tried removing `fast craft` and see if that fixes it?
EDIT: Just checked out the 2.6.3 code and tested in development, stomach drops work perfectly fine.

**Comment by plugnplay0** [comment] 2016-09-09 20:51
Hi IceDragon200, thanks for your quick anwer.
1. Well... That's juste vanilla Milk Bucket. I'm a bit confused, is there any other milk? Isn't right-clicking a cow with a vanilla bucket the thing to do?
2. Oh fine I hadn't notice that change, since I didn't look for thisle yet in 2.6.3.
3. Sorry, what is fast craft?

**Comment by IceDragon200** [comment] 2016-09-09 20:55
@plugnplay0 
1. Milk has no fluid in vanilla, so you need to find out which mod would add the fluid in question
2. yep
3. It's in your mod list; `FASTCRAFT-1.21.jar`

**Comment by plugnplay0** [comment] 2016-09-09 21:55
1. Okay, so let's say I use Growthcraft Milk milk fluid (since I don't use Forestry right now). How do I use the pancheon then? I don't get how to transform vanilla milk bucket into Growthcraft milk fluid.
2. Oh okay sorry about that. I'll try removing FastCraft ASAP.

**Comment by IceDragon200** [comment] 2016-09-09 22:27
@plugnplay0 
1. If you managed to place milk into the Pancheon that means the fluid exists, but isn't recognized by Growthcraft, we have a debug option for dumping the game registry and fluid registry you may need to create a "dumps" directory in your minecraft root path, grab the `FluidRegistry_dump.txt` and look for something "milk" like throw all the names you find at me and I'll add it to 2.6 (2.7 isn't quite ready for use yet)

The config option in question is: 
`$MINECRAFT/config/growthcraft/core.conf`

```
"minecraft/debug" {
    # Should Growthcraft dump the GameRegistry and FluidRegistry to text files?; Default : false
    B:"Enable Game Registry Dump"=true
}
```
1. Let me know if your issue is resolved, the alternative is to start over the mod pack with Growthcraft as the base and gradually add other mods until it stops working correctly

**Comment by plugnplay0** [comment] 2016-09-10 00:13
How weird... it works! I mean, I didn't think that just activating debug mode would fix the problem, only give hints about the potential origin (it's the Java developer in me speaking here ;) ).
Anyway, the pancheon now has a processing progression (in Waila) and works fine, producing 1 Cream bottle for 2 Skim Milk Bottles.
Here are the generated dump files:
- [GameRegistry_Blocks.txt](https://github.com/GrowthcraftCE/Growthcraft-1.7/files/465046/GameRegistry_Blocks.txt)
- [GameRegistry_Items.txt](https://github.com/GrowthcraftCE/Growthcraft-1.7/files/465045/GameRegistry_Items.txt)
- [FluidRegistry_Fluids.txt](https://github.com/GrowthcraftCE/Growthcraft-1.7/files/465047/FluidRegistry_Fluids.txt)

I also removed FastCraft while I was at it, and as a result the stomachs no longer glitch and I can collect them.

Thank you for your help and reactivity. Please let me know if there is some 'cleaner' manner to fix the problem than by activating the debug mode, else I am just as happy :)

**Comment by IceDragon200** [comment] 2016-09-10 02:19
@plugnplay0
Well activating the debug mode doesn't affect any of the code paths except logging (and all I do with that is swap the logger on all the submodules to the parent module's logger)
I see that a "milk" fluid is present, that should work fine, try turning the debug off and see if it causes problems again :)

**Comment by plugnplay0** [comment] 2016-09-10 10:49
I've tried the following things:
1. disabling the debug mode but not putting FastCraft back. Now, the pancheon still works but the stomachs are glitching again. 
2. adding FastCraft 1.23 (from 1.21 before). Now the pancheon still works but the stomachs are still glitching.
3. enabling the debug mode again. No change.
4. removing FastCraft 1.23 and adding FastCraft 1.21 back. Now everything works.

I don't know what to think... It seems the stomachs will work only with FastCraft 1.21 AND debug mode enabled. While the pancheon now works whatever the situation, even in the same situation it didn't before (which makes me wonder if this issue will be fixed on my server).

**Comment by Ghostlyr** [comment] 2016-10-29 11:30
Have a same visual glitch with stomach drops on clean forge client

![2016-10-29_17 31 30](https://cloud.githubusercontent.com/assets/8511068/19829251/9b566d9a-9dfd-11e6-933c-8fc073a73183.png)
![2016-10-29_17 31 38](https://cloud.githubusercontent.com/assets/8511068/19829254/9e3f01f2-9dfd-11e6-88e7-a54dc9dac3c3.png)

**Comment by moxventura** [comment] 2017-09-16 23:40
I saw the stomach glitch too with forge 1.7.10-10.13.4.1558

**Comment by moxventura** [comment] 2017-09-19 07:08
This diff fixes the stomach bug:
```
diff --git a/src/java/growthcraft/milk/eventhandler/EventHandlerOnBabyCowDeath.java b/src/java/growthcraft/milk/eventhandler/EventHandlerOnBabyCowDeath.java
index 884bc986..f3bc57bf 100644
--- a/src/java/growthcraft/milk/eventhandler/EventHandlerOnBabyCowDeath.java
+++ b/src/java/growthcraft/milk/eventhandler/EventHandlerOnBabyCowDeath.java
@@ -51,8 +51,10 @@ public class EventHandlerOnBabyCowDeath
                                        final int count = RandomUtils.range(rng, GrowthCraftMilk.getConfig().stomachMinDropped, GrowthCraftMilk.getConfig().stomachMaxDropped);
                                        if (count > 0)
                                        {
-                                               final ItemStack stack = GrowthCraftMilk.items.stomach.asStack(count);
-                                               ItemUtils.spawnItemStackAtEntity(stack, event.entityLiving, rng);
+                                               if (!event.entity.worldObj.isRemote) {
+                                                       final ItemStack stack = GrowthCraftMilk.items.stomach.asStack(count);
+                                                       ItemUtils.spawnItemStackAtEntity(stack, event.entityLiving, rng);
+                                               }
                                        }
                                }
                        }
```

**Comment by IceDragon200** [comment] 2017-09-19 14:15
@moxventura Thanks for the fix, I've merged your change into dev, unfortunately our build system seems to be broken at the moment so new releases may be delayed, I'll try to get my local builds back up and running and put up a test build (which may have to serve as the official build)

Once anyone has tested and confirmed the fix works, we can close this issue.

Sorry it took so long to be addressed.

EDIT:

Okay a test build is available, it's being hosted on mediafire, my dropbox is packed at the moment

**Comment by moxventura** [comment] 2017-09-20 07:34
Np. It's a classic. :) Glad to help out.
Good work on this mod btw!

**Comment by Alatyami** [comment] 2017-09-24 20:35
I'll look at the build this week and we'll release your fixes. Thanks for adding to the community!

**Closed as completed** 2022-11-15 17:22 UTC
