### ISSUE TITLE
No Mead Bucket Recipe

### ISSUE THREAD

**Issue by nebecanezzar** [GrowthcraftCE/Growthcraft-1.7#417] opened 2016-09-14 07:48 UTC
Hi,

I'm playing resonant rise 3.3 with Growthcraft 1.7-2.6.3 installed. It seems though, that the recipe to create the mead must bucket (water bucket + bucket + honey) is not there. Has the recipe changed or is there another way to create this?

Thanks!

**Comment by IceDragon200** [comment] 2016-09-14 17:28
@nebecanezzar Duplicate of #415, already fixed in development :)

**Closed as completed** 2016-09-26 18:15 UTC
Labels: Fixed in Development
