### ISSUE TITLE
Finite Alcohol?

### ISSUE THREAD

**Issue by killerjdog51** [GrowthcraftCE/Growthcraft-1.7#259] opened 2016-03-15 14:58 UTC
Alright, I think that it'd be cool to be able to do two things. 1st if you were able to right click a source of alcohol with an empty bottle and get the bottle version of that alcohol. Because currently that just gives you water bottles and It just feels weird. But of course just that would break the game, because then you'd be able to get an infinite amount of alcohol from one source block like you can from water. So instead there'd be a finite amount of 1000 millibuckets of alcohol per source block so that when you right click with an empty bottle you only get 3 bottles of alcohol. 

I would like it if this was a feature, but if it us not possible that is understandable. Just thought I would bring it up. Great work on the new milk module btw, its amazing. :D

**Comment by IceDragon200** [comment] 2016-03-15 20:28
@killerjdog51 Bottles picking up water is a known issue, and will not be fixed anytime soon.

**Comment by ghost** [comment] 2016-03-16 18:57
@killerjdog51  the issue is with Minecraft Forge not this mod. there is no way to tell what liquid you are getting and is always water. I have asked @IceDragon200  to provide a bucket to bottle recipe. I think if you fill a bucket of liquid booze then you place the filled bucket with 3 bottles you get 3 filled bottles of booze and an empty bucket.

**Comment by Alatyami** [comment] 2016-03-29 12:29
Going to close this one out as it is a Forge issue. You can transfer buckets to bottles through tanks and various other items.

**Closed as completed by Alatyami** 2016-03-29 12:29 UTC
