### ISSUE TITLE
Building generation cleanup.

### ISSUE THREAD

**Issue by tehFoxx0rz** [GrowthcraftCE/Growthcraft-1.7#144] opened 2015-11-20 22:07 UTC
It's great that the structures now clear their interiors out, but now they clear a bit too much terrain out, causing big holes in the ground around them if they generate sunken into the terrain.  This problem is the biggest with the bee shop, though the farms seem to have a block or so around the edge (http://i.imgur.com/JpyqYu2.png http://i.imgur.com/kV9dOtE.png).  All that needs to be done is make their terrain-clearing (and I guess filling when they generate on a slope) "hug" their footprint more accurately.
It would be great if you could make their steps optional like the vanilla houses (and the tavern actually) too, as that would allow them to have an even smaller footprint and be right next to the paths (and of course have steps only when they need them).

Additionally, I've seen that the orchard generates a grass floor in deserts, but it'd be great if it could have one by default as the floor doesn't always end up being dirt (the bamboo pen might be the same as well); an example here: http://i.imgur.com/YTP2Eze.png (the log floor is me using Better Villages to replace dirt with logs, which can also make this a problem).  You can also see the "one block gap" problem there too, and it also illustrates the last issue to report; that the orchard log border has the logs pointing the wrong way :D

Things are coming on well otherwise with this community continuation and I'm excited to see where it develops; and of course I just want to help it keep its level of quality :D

**Comment by IceDragon200** [comment] 2015-11-21 02:26
I'll consider my buggy village code, well, buggy, thanks for the report, we'll get this fixed (at some point), possibly when I'm not exhausted

**Comment by IceDragon200** [comment] 2015-11-28 17:10
@tehFoxx0rz Looking at your screenshots much closer now, I realize your most likely using the 2.3.1 release, could you try the development builds and report again (I believe I fixed some of these issues early on): see #130 for the builds

I identified the build by the Bee Box by the way, that bee box texture is the old one

**Comment by tehFoxx0rz** [comment] 2015-11-30 11:20
Ah right; I tried the latest build out, and the generation of the orchard seems to be great now, though it could do with having a grass floor ideally still (couldn't find a bamboo pen or rice paddy in my brief search though).  The bee shop however doesn't seem to have changed, though I love the new beebox textures!

**Comment by IceDragon200** [comment] 2015-12-06 16:19
@tehFoxx0rz Would you mind trying the latest build? I just tweaked the village gen issues you mentioned

**Comment by tehFoxx0rz** [comment] 2015-12-08 18:17
The bee houses still seem to be iffy: https://dl.dropboxusercontent.com/u/66131226/2015-12-06_22.43.20.png (though I guess you've not tackled them yet :P)
For the farms though, things look pretty good; grass floors seem to be working (though the paddy didn't need one :P), and the "fill" blocks seem to only be generating underneath the farms' actual footprints now, which is great, though they (all) still seem to have an extra block or so around a few of their edges which they either clear out or generate the grass in: https://dl.dropboxusercontent.com/u/66131226/2015-12-07_00.05.50.png  https://dl.dropboxusercontent.com/u/66131226/2015-12-08_17.18.26.png
And the orchards seem to cut the tops of their trees off now and again :P  https://dl.dropboxusercontent.com/u/66131226/2015-12-07_00.22.45.png
And I noticed that the bamboo pens don't seem to orientate their doors appropriately to the rotation of the pen, but this is a much smaller issue!

Thanks for being so responsive though (all of you); the mod certainly seems to be in good hands!

**Comment by IceDragon200** [comment] 2015-12-08 18:40
@tehFoxx0rz Bee House, that's not a :beetle:**bug**, thats a :star:**feature**! I kid you not, that patch of dirt is generated above the ground because design reasons.

As for the extra border, ahhh, I need to fix that specially, some of the buildings have rectangular shapes, so I just a all encompassing square, because of laziness

Orchards, I was trying to figure that one out myself, I set the bb to 11^3, which is 11x11x11 but IT STILL CHOPS THEM OFF.

**Comment by tehFoxx0rz** [comment] 2015-12-08 20:32
The problem with the bee house is that it clears out all that area, and generates fill material under all of that area; that house behind it has been munched into by its clear area, and that cobblestone generated as its fill material.. Other pictures for clarity: https://dl.dropboxusercontent.com/u/66131226/2015-12-06_20.17.47.png https://dl.dropboxusercontent.com/u/66131226/2015-12-06_20.24.52.png
It could just do with some bounding box trimming like the farms :P

**Comment by ghost** [comment] 2015-12-09 03:41
I'll say the Village Generation has improved dramatically over the first release of 2.3.0 and I personally have not found any major issues.  One thing I noticed is sometimes the bamboo yard or rice field sometimes does not have any bamboo/rice planted in it. It's an odd thing caused by terrain that interferes with the generation. But is very rare occurrence. I don't think this should be a focus right now.

**Comment by tehFoxx0rz** [comment] 2015-12-09 12:45
This is hopefully what the grass floors will mitigate :P  Admittedly they can still get things like gravel or sand replacing it and causing problems apparently, but it should be less of a certain issue than not getting a floor when they cut into terrain.  And the vanilla houses with the garden have a similar problem anyway.
Did you try out the latest build?

**Comment by Alatyami** [comment] 2016-01-01 16:03
We are going to close this one out. If anyone finds any more issues please open another ticket.

**Closed as completed by Alatyami** 2016-01-01 16:03 UTC
Labels: Bug
