### ISSUE TITLE
Crash in ModPack due to NSMError: ItemStack.getItem()

### ISSUE THREAD

**Issue by Th3Night4ngel** [GrowthcraftCE/Growthcraft-1.7#188] opened 2016-01-17 19:28 UTC
I was messing aroud trying to make my own modpack, and I encoutered this exception (GrowthCraft 2.4.0) during the "transition from **PREINIT** to **INIT**." I'm using Forge 1566 build, tried with 1614 too.

[> Crash report <](http://pastebin.com/kaQrRrSu)

I'm using MultiMC to easily manage the project.

**Comment by Alatyami** [comment] 2016-01-17 20:13
Thank you for the report. My personal modpack is very similar. We'll take a look and see what the issue is. I am not seeing the error with my modpack so there might be a conflicting mod that has an overload. Can you export your MultiMC instance (just keep the mod folder) and give us a link? Otherwise we'll have to recreate your modpack list from the logs and it'll take longer to get you a fix.

**Comment by IceDragon200** [comment] 2016-01-17 20:18
@Th3Night4ngel Uggggh noooes, more bugs! 

Complaints aside, have you tried running the mod alone with MultiMC, and without?
If the problem persists, then its our problem, but if it only happens in MultiMC, its best you ask them "waddup?"

Because if it works just fine by itself, then something messed with Minecraft's code.

**Comment by Th3Night4ngel** [comment] 2016-01-18 13:54
Sorry for the late answer! 

@IceDragon200  I ran some tests and seems that MultiMC with forge 1566 build and only GrowthCraft installed (complete version) works fine. 

@Alatyami I haven't a very fast connection, so IDK how much it would take to upload the mods folder (if it is that what you need)... With the best archiving method of WinRAR I still got to upload 214 MB of jar files, and it takes me 1 min and more to upload 1 MB... What I can do is prepare a txt file with all the download links. I don't believe my connection would support such an upload. Sorry ;(

**Comment by IceDragon200** [comment] 2016-01-18 15:14
@Th3Night4ngel : I think you can eliminate a few mods as culprits,
- Thaumcraft
- AgriCraft (this is only temporary until we fix the rice paddy issue)
- Buildcraft
- Forestry
- WAILA
- NEI

I run all of these in development, so if you want to, you can start a fresh mod pack with all of those in as the base, and then gradually add the other mods, I know it takes awhile, but once you pinpoint the mod that breaks the game you can try to figure out what combination of mods causes it to spaz out.

For starters, you can add the "Cores", mods that act as a base for others one by one since those are likely to have a coremod that modifies minecraft directly

**Comment by Th3Night4ngel** [comment] 2016-01-18 17:00
Ok, that's strange... I remade the modpack in a new instance and It didn't crash anymore... ok... seems there is no bug at all, maybe a currupted file in the minecraft jar or some broken stuff, IDK

**Comment by IceDragon200** [comment] 2016-01-18 17:09
Or you grabbed a dev version of a jar, well glad you don't have anymore problems, feel free to close the issue

**Comment by Alatyami** [comment] 2016-01-18 17:22
One that gets me sometimes is the forge multipart in mods/1.7.10

Alatyami

**Comment by IceDragon200** [comment] 2016-01-25 23:33
Closing this since it was solved

**Closed as completed by IceDragon200** 2016-01-25 23:33 UTC
